language: go
sudo: required

go_import_path: github.com/water-hole/ansible-operator

env:
  - CHANGE_MINIKUBE_NONE_USER=true

install:
  # setup operator-sdk
  - go get github.com/golang/dep/cmd/dep
  - mkdir -p $GOPATH/src/github.com/operator-framework
  - cd $GOPATH/src/github.com/operator-framework
  - git clone https://github.com/operator-framework/operator-sdk
  - cd operator-sdk
  - git checkout master
  - make dep
  - make install
  - cd $GOPATH/src/github.com/water-hole/ansible-operator
  - operator-sdk build quay.io/water-hole/ansible-operator

jobs:
  include:
    - stage: test
      before_script:
        # setup minikube
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.11.2/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.25.2/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
        - curl -Lo oc.tar.gz https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
        - tar xvzOf oc.tar.gz openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/oc > oc && chmod +x oc && sudo mv oc /usr/local/bin/
          # - sudo minikube start --vm-driver=none --kubernetes-version=v1.9.0
          # - minikube update-context
        - sudo service docker stop
        - sudo sed -i 's/DOCKER_OPTS=\"/DOCKER_OPTS=\"--insecure-registry 172.30.0.0\/16 /' /etc/default/docker
        - sudo service docker start

        - oc cluster up
        - oc login -u system:admin
        # Wait until node is ready
        - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
      script:
        # create example CRD and operator
        - pushd example
        - kubectl create -f deploy/rbac.yaml
        - kubectl create -f deploy/crd.yaml
        - kubectl create -f deploy/operator.yaml

        # wait for operator pod to run
        - kubectl rollout status deployment/ansible-operator
        - kubectl logs deployment/ansible-operator

        # set a test string, build example operator from previously built base image
        - sed -i s/hello\ world/travis\ test/g roles/busybox/defaults/main.yml
        - docker build -f build/Dockerfile -t busybox-ansible-operator-test:test .
        - kubectl patch deployment ansible-operator -p '{"spec":{"template":{"spec":{"containers":[{"name":"ansible-operator","imagePullPolicy":"Never"}]}}}}'
        - kubectl set image deployment/ansible-operator *=busybox-ansible-operator-test:test

        # wait for operator rollout
        - kubectl rollout status deployment/ansible-operator
        - kubectl logs deployment/ansible-operator

        # deploy example resource and check for test string
        - kubectl create -f deploy/cr.yaml
        - (kubectl get deployment | grep busybox) ; while [ $? -ne 0 ] ; do sleep 5 && kubectl get deployment && (kubectl get deployment | grep busybox) ; done
        - busybox_deployment=$(kubectl get deployment | grep busybox | awk '{print $1}')
        - kubectl rollout status deployment/${busybox_deployment}
        - kubectl logs deployment/${busybox_deployment} | grep "travis test"
        - kubectl delete -f deploy/cr.yaml
        # Test finalizer
        - kubectl wait database/example --for=delete --timeout=1m || true
        - kubectl logs deployment/ansible-operator | grep "finalizer_running"

    - stage: deploy
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin quay.io
        - docker tag quay.io/water-hole/ansible-operator quay.io/water-hole/ansible-operator
        - docker push quay.io/water-hole/ansible-operator
        - cd $GOPATH/src/github.com/water-hole/ansible-operator/example
        - docker build -f build/Dockerfile -t quay.io/water-hole/busybox-ansible-operator .
        - docker push quay.io/water-hole/busybox-ansible-operator

    - stage: deploy-release
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin quay.io
        - docker tag quay.io/water-hole/ansible-operator quay.io/water-hole/ansible-operator:${TRAVIS_TAG}
        - docker push quay.io/water-hole/ansible-operator:${TRAVIS_TAG}
        - cd $GOPATH/src/github.com/water-hole/ansible-operator/example
        - docker build -t quay.io/water-hole/busybox-ansible-operator:${TRAVIS_TAG} .
        - docker push quay.io/water-hole/busybox-ansible-operator:${TRAVIS_TAG}
stages:
  - test
  - name: deploy
    if: (tag IS blank) AND (branch = master) AND (type = push)
  - name: deploy-release
    if: (tag IS present) AND (type = push)
